### ISSUE TITLE
could you please upload nutch-site.xml  ?

### ISSUE THREAD

**Issue by parkkichul** [mdigiacomi/indexer-elastic#3]
could you please upload nutch-site.xml  ?

how did you set up with "plugin.inculdes"?

i do build ant runtime successfully.  but when i bin/nutch index -all. it notice error like indexer blah blah.

nutch_site.xml

<property>
    <name>plugin.includes</name>
<value>protocol-(http|httpclient)|urlfilter-regex|index-(basic|more)|query-(basic|site|url|lang)|indexer-elastic|nutch-extensionpoints|parse-(text|html|msexcel|msword|mspowerpoint|pdf)|summary-basic|scoring-opic|urlnormalizer-(pass|regex|basic)|parse-(html|tika|metatags)|index-(basic|anchor|more|metadata)</value>
  </property>

**Comment by mdigiacomi** [comment]
`<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>



<configuration>
<property>
    <name>elastic.host</name>
    <value>192.168.0.53</value>
</property>
<property>
    <name>elastic.port</name>
    <value>9300</value>
</property>
<property>
    <name>elastic.cluster</name>
    <value>elasticsearch</value>
</property>
<property>
    <name>elastic.index</name>
    <value>nutchindex</value>
</property>
<property>
  <name>elastic.max.bulk.docs</name>
  <value>250</value>
  <description>Maximum size of the bulk in number of documents.</description>
</property>
<property>
  <name>elastic.max.bulk.size</name>
  <value>2500500</value>
  <description>Maximum size of the bulk in bytes.</description>
</property>
</configuration>
`

**Comment by mdigiacomi** [comment]
Plugin include is not included in nutch_site.xml

**Comment by mdigiacomi** [comment]
I don't modify the plugin list. This code is to be a complete replacement for the current indexer.
