### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by ssedumeone** [mdigiacomi/indexer-elastic#4]
I get this when I do ant runtime what am I doing wrong?
compile:
```
     [echo] Compiling plugin: indexer-elastic
    [javac] Compiling 3 source files to /usr/local/nutch/build/indexer-elastic/classes
    [javac] /usr/local/nutch/src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java:83: error: cannot find symbol
    [javac]     Settings settings = Settings.builder().put("cluster.name", clusterName).build();
    [javac]                                 ^
    [javac]   symbol:   method builder()
    [javac]   location: interface Settings
    [javac] 1 error

BUILD FAILED
/usr/local/nutch/build.xml:113: The following error occurred while executing this line:
/usr/local/nutch/src/plugin/build.xml:36: The following error occurred while executing this line:
/usr/local/nutch/src/plugin/build-plugin.xml:117: Compile failed; see the compiler error output for details.


```

**Comment by mdigiacomi** [comment]
What version of butch are you testing this with?

**Comment by mdigiacomi** [comment]
I mean Nutch not butch

**Comment by ssedumeone** [comment]
Sorry had clones the indexer-elastic in another nutch dir :-) but getting another error.
am using nutch 2.3 
and getting this error now 
Caused by: java.io.FileNotFoundException: /usr/local/nutch/src/plugin/indexer-elastic/ivy/ivy-configurations.xml (No such file or directory)

**Comment by ssedumeone** [comment]
I guess it's not in the indexer-elastic clone

**Comment by ssedumeone** [comment]
Found anything interesting? still come here
`[ivy:resolve] :: loading settings :: file = /usr/local/nutch/ivy/ivysettings.xml

compile:
     [echo] Compiling plugin: indexer-elastic
    [javac] Compiling 3 source files to /usr/local/nutch/build/indexer-elastic/classes
    [javac] /usr/local/nutch/src/plugin/indexer-elastic/src/java/org/apache/nutch/indexwriter/elastic/ElasticIndexWriter.java:83: error: cannot find symbol
    [javac]     Settings settings = Settings.builder().put("cluster.name", clusterName).build();
    [javac]                                 ^
    [javac]   symbol:   method builder()
    [javac]   location: interface Settings
    [javac] 1 error

BUILD FAILED
/usr/local/nutch/build.xml:113: The following error occurred while executing this line:
/usr/local/nutch/src/plugin/build.xml:36: The following error occurred while executing this line:
/usr/local/nutch/src/plugin/build-plugin.xml:117: Compile failed; see the compiler error output for details.

Total time: 39 second
usr/local/nutch# `

**Comment by mdigiacomi** [comment]
I just tried building 2.3 from scratch using the readme instructions and I didn't get an error

**Comment by mdigiacomi** [comment]
```xml
runtime:
    [mkdir] Created dir: /home/mdigiacomi/apache-nutch-2.3/runtime
    [mkdir] Created dir: /home/mdigiacomi/apache-nutch-2.3/runtime/local
    [mkdir] Created dir: /home/mdigiacomi/apache-nutch-2.3/runtime/deploy
     [copy] Copying 1 file to /home/mdigiacomi/apache-nutch-2.3/runtime/deploy
     [copy] Copying 2 files to /home/mdigiacomi/apache-nutch-2.3/runtime/deploy/bin
     [copy] Copying 1 file to /home/mdigiacomi/apache-nutch-2.3/runtime/local/lib
     [copy] Copying 1 file to /home/mdigiacomi/apache-nutch-2.3/runtime/local/lib/native
     [copy] Copying 30 files to /home/mdigiacomi/apache-nutch-2.3/runtime/local/conf
     [copy] Copying 2 files to /home/mdigiacomi/apache-nutch-2.3/runtime/local/bin
     [copy] Copying 224 files to /home/mdigiacomi/apache-nutch-2.3/runtime/local/lib
     [copy] Copying 181 files to /home/mdigiacomi/apache-nutch-2.3/runtime/local/plugins
     [copy] Copied 2 empty directories to 2 empty directories under /home/mdigiacomi/apache-nutch-2.3/runtime/local/test

BUILD SUCCESSFUL
Total time: 26 seconds
```

**Comment by ssedumeone** [comment]
Very good followed it well and  I managed to build it now fighting with indexing with indexer-elastic

**Comment by mdigiacomi** [comment]
I've never run it against elasticsearch 2.3. This version is for 5.0+ mostly. I think there were indexing differences between 2.x and 5.x which is why I built this

**Comment by ssedumeone** [comment]
Thanks Michael
am here now  bin/nutch index afromoja -all
IndexingJob: starting
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Active IndexWriters :
ElasticIndexWriter
	elastic.cluster : elastic prefix cluster
	elastic.host : hostname
	elastic.port : port  (default 9300)
	elastic.index : elastic index command 
	elastic.max.bulk.docs : elastic bulk index doc counts. (default 250) 
	elastic.max.bulk.size : elastic bulk index length. (default 2500500 ~2.5MB)


IndexingJob: done.
